import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { sendEmail } from './email'

interface BudgetData {
  category: string
  budgeted: number
  spent: number
  remaining: number
  percentage: number
  status: string
}

interface BudgetSummary {
  totalBudgeted: number
  totalSpent: number
  totalRemaining: number
  overallPercentage: number
  month: string
  year: number
}

export async function exportBudgetToPDF(
  budgets: BudgetData[],
  summary: BudgetSummary,
  userEmail?: string
) {
  try {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()

    // Header
    doc.setFillColor(59, 130, 246) // Blue
    doc.rect(0, 0, pageWidth, 45, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(26)
    doc.setFont('helvetica', 'bold')
    doc.text('MONTHLY BUDGET REPORT', pageWidth / 2, 18, { align: 'center' })

    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text(`${summary.month} ${summary.year}`, pageWidth / 2, 28, { align: 'center' })

    if (userEmail) {
      doc.setFontSize(9)
      doc.text(`Account: ${userEmail}`, pageWidth / 2, 36, { align: 'center' })
    }

    const today = new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric'
    })
    doc.setFontSize(8)
    doc.text(`Generated: ${today}`, pageWidth - 14, 16, { align: 'right' })

    doc.setTextColor(0, 0, 0)

    // Summary Section
    let yPos = 55
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Budget Summary', 14, yPos)

    yPos += 10
    const summaryData = [
      ['Total Budgeted', `₹${summary.totalBudgeted.toLocaleString()}`],
      ['Total Spent', `₹${summary.totalSpent.toLocaleString()}`],
      ['Total Remaining', `₹${summary.totalRemaining.toLocaleString()}`],
      ['Overall Usage', `${summary.overallPercentage}%`]
    ]

    autoTable(doc as any, {
      startY: yPos,
      head: [],
      body: summaryData,
      theme: 'grid',
      styles: {
        fontSize: 10,
        cellPadding: 5
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 60 },
        1: { halign: 'right', fontStyle: 'bold' }
      }
    })

    // Category Breakdown
    yPos = (doc as any).lastAutoTable.finalY + 15
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Category Breakdown', 14, yPos)

    yPos += 5
    const tableData = budgets.map(budget => [
      budget.category,
      `₹${budget.budgeted.toLocaleString()}`,
      `₹${budget.spent.toLocaleString()}`,
      `₹${budget.remaining.toLocaleString()}`,
      `${budget.percentage}%`,
      budget.status.toUpperCase()
    ])

    autoTable(doc as any, {
      startY: yPos,
      head: [['Category', 'Budgeted', 'Spent', 'Remaining', 'Used', 'Status']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [59, 130, 246],
        textColor: 255,
        fontStyle: 'bold',
        fontSize: 10
      },
      styles: {
        fontSize: 9,
        cellPadding: 4
      },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'center' },
        5: { halign: 'center', fontStyle: 'bold' }
      },
      didParseCell: function (data: any) {
        if (data.column.index === 5 && data.section === 'body') {
          const status = data.cell.text[0]
          if (status === 'OVER') {
            data.cell.styles.textColor = [220, 38, 38]
          } else if (status === 'WARNING') {
            data.cell.styles.textColor = [245, 158, 11]
          } else if (status === 'GOOD') {
            data.cell.styles.textColor = [34, 197, 94]
          }
        }
      }
    })

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(128, 128, 128)
      doc.text(
        `Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      )
      doc.text(
        'Generated by Expense Tracker',
        14,
        doc.internal.pageSize.getHeight() - 10
      )
    }

    return doc
  } catch (error) {
    console.error('Error generating budget PDF:', error)
    throw error
  }
}

export async function sendBudgetEmail(
  budgets: BudgetData[],
  summary: BudgetSummary,
  userEmail: string,
  userName: string
) {
  try {
    // Generate PDF
    const doc = await exportBudgetToPDF(budgets, summary, userEmail)
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'))
    const pdfBase64 = pdfBuffer.toString('base64')

    // Create HTML email
    const statusColor = (status: string) => {
      switch (status) {
        case 'good': return '#10b981'
        case 'warning': return '#f59e0b'
        case 'over': return '#ef4444'
        default: return '#3b82f6'
      }
    }

    const budgetRows = budgets.map(budget => `
      <tr style="border-bottom: 1px solid #e5e7eb;">
        <td style="padding: 12px; font-weight: 500;">${budget.category}</td>
        <td style="padding: 12px; text-align: right;">₹${budget.budgeted.toLocaleString()}</td>
        <td style="padding: 12px; text-align: right;">₹${budget.spent.toLocaleString()}</td>
        <td style="padding: 12px; text-align: right;">₹${budget.remaining.toLocaleString()}</td>
        <td style="padding: 12px; text-align: center;">
          <span style="background: ${statusColor(budget.status)}20; color: ${statusColor(budget.status)}; padding: 4px 12px; border-radius: 12px; font-weight: 600; font-size: 12px;">
            ${budget.percentage}%
          </span>
        </td>
      </tr>
    `).join('')

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f3f4f6;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff;">
          <!-- Header -->
          <div style="background: linear-gradient(135deg, #3b82f6 0%, #6366f1 100%); padding: 40px 20px; text-align: center;">
            <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 700;">Monthly Budget Report</h1>
            <p style="color: #e0e7ff; margin: 10px 0 0 0; font-size: 16px;">${summary.month} ${summary.year}</p>
          </div>

          <!-- Content -->
          <div style="padding: 30px 20px;">
            <p style="color: #374151; font-size: 16px; margin: 0 0 20px 0;">Hi ${userName},</p>
            <p style="color: #6b7280; font-size: 14px; line-height: 1.6; margin: 0 0 30px 0;">
              Here's your monthly budget report. The detailed PDF is attached to this email.
            </p>

            <!-- Summary Cards -->
            <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin-bottom: 30px;">
              <div style="background: #f9fafb; border-radius: 12px; padding: 20px; border: 1px solid #e5e7eb;">
                <p style="color: #6b7280; font-size: 12px; margin: 0 0 8px 0; text-transform: uppercase; letter-spacing: 0.5px;">Total Budget</p>
                <p style="color: #111827; font-size: 24px; font-weight: 700; margin: 0;">₹${summary.totalBudgeted.toLocaleString()}</p>
              </div>
              <div style="background: #fef2f2; border-radius: 12px; padding: 20px; border: 1px solid #fecaca;">
                <p style="color: #991b1b; font-size: 12px; margin: 0 0 8px 0; text-transform: uppercase; letter-spacing: 0.5px;">Total Spent</p>
                <p style="color: #dc2626; font-size: 24px; font-weight: 700; margin: 0;">₹${summary.totalSpent.toLocaleString()}</p>
              </div>
              <div style="background: #f0fdf4; border-radius: 12px; padding: 20px; border: 1px solid #bbf7d0;">
                <p style="color: #166534; font-size: 12px; margin: 0 0 8px 0; text-transform: uppercase; letter-spacing: 0.5px;">Remaining</p>
                <p style="color: #16a34a; font-size: 24px; font-weight: 700; margin: 0;">₹${summary.totalRemaining.toLocaleString()}</p>
              </div>
              <div style="background: #eff6ff; border-radius: 12px; padding: 20px; border: 1px solid #bfdbfe;">
                <p style="color: #1e40af; font-size: 12px; margin: 0 0 8px 0; text-transform: uppercase; letter-spacing: 0.5px;">Overall Usage</p>
                <p style="color: #2563eb; font-size: 24px; font-weight: 700; margin: 0;">${summary.overallPercentage}%</p>
              </div>
            </div>

            <!-- Budget Table -->
            <div style="background: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #e5e7eb; margin-bottom: 30px;">
              <table style="width: 100%; border-collapse: collapse;">
                <thead>
                  <tr style="background: #f9fafb;">
                    <th style="padding: 12px; text-align: left; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase;">Category</th>
                    <th style="padding: 12px; text-align: right; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase;">Budget</th>
                    <th style="padding: 12px; text-align: right; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase;">Spent</th>
                    <th style="padding: 12px; text-align: right; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase;">Left</th>
                    <th style="padding: 12px; text-align: center; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase;">Used</th>
                  </tr>
                </thead>
                <tbody>
                  ${budgetRows}
                </tbody>
              </table>
            </div>

            <p style="color: #6b7280; font-size: 13px; line-height: 1.6; margin: 0;">
              Keep tracking your expenses to stay within your budget. Your budget will automatically reset on the 11th of next month.
            </p>
          </div>

          <!-- Footer -->
          <div style="background: #f9fafb; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb;">
            <p style="color: #9ca3af; font-size: 12px; margin: 0;">
              Generated by Expense Tracker • ${new Date().toLocaleDateString()}
            </p>
          </div>
        </div>
      </body>
      </html>
    `

    await sendEmail({
      to: userEmail,
      subject: `Monthly Budget Report - ${summary.month} ${summary.year}`,
      html,
      text: `Your monthly budget report for ${summary.month} ${summary.year} is attached.`,
      attachments: [
        {
          filename: `budget-${summary.month}-${summary.year}.pdf`,
          content: pdfBase64,
          encoding: 'base64'
        }
      ]
    })

    return true
  } catch (error) {
    console.error('Error sending budget email:', error)
    throw error
  }
}
